### ISSUE TITLE
Оценка работы

### ISSUE THREAD

**Issue by goliksim** [Kondrashov16/YandexToDo#1]
# Оценка кросспроверки
Привет, оценивал твоё приложение на кросс проверке. В целом твой подход к проектированию похож на мой) <br/>
Но я хотел отменить некоторые замечания:
- Не нашел в репозитории пул реквест, так что пишу в ошибках.
### По части UI
- **UI не совпадает с макетом в фигме**:
-- **Текст не режеться**, если содержимое очень длинное.
-- **Кнопка отображения** сделанных задач **куда-то уезжает**, хотя на макете она есть во всех сценариях.
-- **Отступы** вроде константные, но **не соответствуют макету** в некоторых местах.
- **Маленькие кнопки**. Ты делал их через TextButton, не увеличивая область, так что попадать по ним немного трудно, можно было сделать кнопочки на всю ширину экрана.
- **Кнопка удалить** из себя представляет две отдельных кнопки: одна на иконке, другая на тексте. Зачем?
### По части кода
- Вместо функции проверки на режим работы окна редактирования (**isTaskNew**) можно прокидывать в виджет сразу константный bool. 
- Вместо **кучи функций импорта значений** задачи можно просто пользоваться значениями объекта. А при создании нового, передавать в EditPage Task без начальных значений.
- Имхо не обязательно было использование **отдельной переменной для количества выполненных дел**. Это число нужно в 1 месте кода и можно было спокойно использовать конструкцию типа myTasks.where((e)=> e.isDone).lenght
### Не ошибки, но замечания
- Нет персистентности
- Файл называется tasks_list, но виджет назвал HomePage. Небольшая несостыковка.
- Хоть это и не ошибка, но не понял зачем ставить **дедлайн в прошлом**.
- В пикере приоритетов все супер захардкожено, хотя идея с **PopUpMenuButton** мне понравилась, сам лично использовал DropdownMenu.
- Использование константных цветов в виджетах, намного проще было бы **использования темы**, куда можно загрузить все цвета и обращаться к именнованым переменным через контекст по необходимости.
- Не очень понял, зачем было использовать **SliverToBoxAdapter на второй странице**. Там от нас этого уже не требовалось.
<img src="https://github.com/Kondrashov16/YandexToDo/assets/66952748/23a629fb-05ce-4e4b-b730-97a16b5a78b0" width="200" height="400" />

**Comment by Kondrashov16** [comment]
Привет

**Comment by Kondrashov16** [comment]
Привет
Спасибо за проверку и замечания!
По верстке все так, криво получилось, торопился (как раз про отступы и обрезку текста) и в паре моментов не понял, как сделать все правильно (дурацкий логотип глаза как раз про это)).
Спасибо за остальные советы и замечания, учту обязательно.
