### ISSUE TITLE
Ревью второго ДЗ

### ISSUE THREAD

**Issue by MedVAL-na** [Kondrashov16/YandexToDo#4]
Привет!
Приложение очень классное, работает очень плавно, переход со страницы на страницу ровный - очень приятный UI, было бы вообще идеально если бы расстояние между title "мои дела" и subtitle "важность" было бы на пару пикселей больше, т.к. например в англоязычной версии буквы немного наезжают друг на друга.
По поводу стейт-менеджмента: реализация на statefull - сильно, очень сильно.
Советую посмотреть для дальнейшей реализации на Bloc (например, вот этот [туториал](https://www.youtube.com/watch?v=rVI6IR1JiVA&t=292s&ab_channel=HeyFlutter%E2%80%A4com) или [доку](https://bloclibrary.dev/#/)).
Из минусов: 
1) код до конца не отформатирован: по команде **dart format** ide отформатировала код, 
2) flutter lints конечно добавлен, но по команде **dart analyze** выпало очень много игноров правил

**_Итого по критериям:_**
1) актуальное README с ссылкой на apk +1 балл
2) flutter lints добавлен, но не использован +0.5 баллов
3) формат кода есть, но не на весь проект +0.5 баллов
4) код разбит на слои +2 балла
5) state managment +5 баллов (на statefull - бесценно)
6) переключение плавное, ничего нигде не скачет +3 балла
7) back есть, но не до конца +1.5 балла
8) работа с сетью выделена в отдельный слой +2 балла
9) Работа с БД есть и все работает +3 балла
10) Работа с БД выделена в отдельный слой +2 балла
11) работа с async есть, мешанины нет + 1 балл
12) интернационализация есть и работает + 2 балла

Сумма: **23.5 балла**

**Comment by Kondrashov16** [comment]
Привет!
Работа со стейтом используя стейтфулл виджеты и правда проведена крайне серьезно и качественно, спасибо за признание этой особенности (вообще я в процессе переезда на риверпод просто, а блок совсем не нравится из-за количества boilerplate-кода). 
Про **dart analyze** достаточно странно, потому что я проверял (в том числе и с **flutter analyze**) и не было ничего. Сейчас проверил снова, тоже все хорошо. Вероятно сделал что-то не так и не понимаю что)
Спасибо за ревью!
