### ISSUE TITLE
[Stage 3] Review

### ISSUE THREAD

**Issue by olegalibekov** [Kondrashov16/YandexToDo#7]
Чистота кода и общая структура проекта (max 5 баллов)
* Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов (0.5/1 балла) – APK был невалидный
* Добавлен и работает flutter_lints, в коде нет необоснованных игноров правил (1/1 балла)
* Форматирование кода присутствует (1/1 балла)
* Код разбит на фичи и слои (не важно, feature-first / layer-first) (2/2 баллов)

Получение и хранение данных (max 6 баллов)
* Реализована обработка серверных и прочих ошибок там, где они могут часто стрелять (2/2 баллов)
* Приложение адекватно работает без интернета (2/2 баллов)
    * Offline-first: работа без интернета возможна полноценно, при последующем запуске дошлётся то, что не смогло уйти в предыдущей сессии из-за ошибок/отсутствия сети (2/2 баллов)

Architecture (max 7 баллов)
* Работа с данными организована в отдельной сущности, репозитории, инкапсулируя в одном месте получение и обновление/добавление данных на диск (3/3 баллов)

* State-management реализован с использованием одного из предложенных фреймворков (0/2 баллов) – зависимость Riverpod есть, но без реализации

* Есть DI (Riverpod, Service Locator, контейнеры зависимостей или библиотеки) (0/2 баллов) – есть ProviderScope без реализации

Testing (max 5 баллов)
* Unit-тестами покрыты сущности с бизнес-логикой, тест осмысленный и полезный (+1 балл за тест каждой сущности (например, класс для работы с сетью, класс для работы с БД, репозиторий)) в пределах +3 баллов) (0/3 баллов)

В случае:
- database_local_test.dart: тест другой реализации БД (class MockTasksDatabase implements TasksDatabase)
- database_server_test.dart: нет перехвата запроса и мокового ответа + тест другой реализации БД (class MockServerDatabase implements ServerDatabase)
- task_test.dart: один тест малоприменимый (уникальное время создания) + не хватает покрытия других методов Task класса

* Реализован интеграционный тест, покрывающий один из сценариев работы (например, добавление дела) (0/2 баллов) – крашится (логи ниже)

Deeplinks (max 3 балла)
* Поддержан диплинк, открывающий экран добавления нового дела (0/1 балла)
* Диплинк открывается даже если приложение было убито (0/1 балла)
* Слой навигации переписан на Navigator 2.0 (0/1 балл)

Логи краша:

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with text "!! Высокий" (ignoring offstage widgets)" (used in a call to
"tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1293:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1232:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/fehty/StudioProjects/YandexToDo/integration_test/add_task_test.dart:37:20)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  complete test of adding a task
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: complete test of adding a task

**Comment by olegalibekov** [comment]
Чистота кода и общая структура проекта (max 5 баллов)
* Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов (0.5/1 балла) – APK был невалидный
* Добавлен и работает flutter_lints, в коде нет необоснованных игноров правил (1/1 балла)
* Форматирование кода присутствует (1/1 балла)
* Код разбит на фичи и слои (не важно, feature-first / layer-first) (2/2 баллов)
Получение и хранение данных (max 6 баллов)
* Реализована обработка серверных и прочих ошибок там, где они могут часто стрелять (2/2 баллов)
* Приложение адекватно работает без интернета (2/2 баллов)
    * Offline-first: работа без интернета возможна полноценно, при последующем запуске дошлётся то, что не смогло уйти в предыдущей сессии из-за ошибок/отсутствия сети (2/2 баллов)

Architecture (max 7 баллов)
* Работа с данными организована в отдельной сущности, репозитории, инкапсулируя в одном месте получение и обновление/добавление данных на диск (3/3 баллов)

* State-management реализован с использованием одного из предложенных фреймворков (0/2 баллов) – зависимость Riverpod есть, но без реализации

* Есть DI (Riverpod, Service Locator, контейнеры зависимостей или библиотеки) (0/2 баллов) – есть ProviderScope без реализации

Testing (max 5 баллов)
* Unit-тестами покрыты сущности с бизнес-логикой, тест осмысленный и полезный (+1 балл за тест каждой сущности (например, класс для работы с сетью, класс для работы с БД, репозиторий)) в пределах +3 баллов) (0/3 баллов)

В случае
- database_local_test.dart: тест другой реализации БД (class MockTasksDatabase implements TasksDatabase)
- database_server_test.dart: нет перехвата запроса и мокового ответа + тест другой реализации БД (class MockServerDatabase implements ServerDatabase)
- task_test.dart: один тест малоприменимый (уникальное время создания) + не хватает покрытия других методов Task класса

* Реализован интеграционный тест, покрывающий один из сценариев работы (например, добавление дела) (0/2 баллов) – крашится (логи ниже)

Deeplinks (max 3 балла)
* Поддержан диплинк, открывающий экран добавления нового дела (0/1 балла)
* Диплинк открывается даже если приложение было убито (0/1 балла)
* Слой навигации переписан на Navigator 2.0 (0/1 балл)

Логи краша:

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with text "!! Высокий" (ignoring offstage widgets)" (used in a call to
"tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1293:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1232:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/fehty/StudioProjects/YandexToDo/integration_test/add_task_test.dart:37:20)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  complete test of adding a task
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: complete test of adding a task

**Comment by LilyKras** [comment]
У меня примерно так же, но 1/2 баллов за офлайн, тк вроде не должно быть такого, что на разных устройствах разный список тасков. У меня это как-то получилось…

Кстати по поводу информации о девайсе - там из-за неё возникают проблемы при сборке на айфоне.
